# Generated by Django 2.1.2 on 2018-10-10 09:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='posted',
            new_name='posted_on',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='New Post', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=blog.models.thumbnail),
        ),
    ]
