# Generated by Django 2.1.2 on 2018-12-26 19:00

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181102_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
